# Generated by Django 2.1.7 on 2020-01-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_str', models.CharField(max_length=50, unique=True, verbose_name='账号信息')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('sale_time', models.DateTimeField(blank=True, null=True, verbose_name='出售时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否出售')),
            ],
            options={
                'verbose_name_plural': '账号信息',
            },
        ),
        migrations.CreateModel(
            name='LevelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True, verbose_name='级别')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('description', models.CharField(max_length=255, verbose_name='级别简介')),
            ],
            options={
                'verbose_name_plural': '账号级别',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(default='default.jpg', upload_to='avatar/')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='类型')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('description', models.CharField(max_length=255, verbose_name='类型简介')),
            ],
            options={
                'verbose_name_plural': '账号类型',
            },
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('currency', models.IntegerField(choices=[(0, '人民币'), (1, '美元')], default=0, verbose_name='货币')),
                ('unit', models.CharField(default='个', max_length=10, verbose_name='单位')),
                ('isDelete', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_goods.LevelInfo', verbose_name='级别')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_goods.TypeInfo', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '单位价格',
            },
        ),
    ]
