# Generated by Django 2.1.7 on 2020-01-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_goods', '0001_initial'),
        ('ac_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_order.OrderInfo'),
        ),
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_goods.UnitPrice', verbose_name='价格'),
        ),
        migrations.AlterUniqueTogether(
            name='unitprice',
            unique_together={('type', 'level')},
        ),
    ]
