# Generated by Django 2.1.7 on 2020-01-05 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_goods', '0002_auto_20200106_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_sale_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 13, 1, 19, 32793), verbose_name='可售时间'),
        ),
        migrations.AddField(
            model_name='account',
            name='isSale',
            field=models.BooleanField(default=False, verbose_name='是否出售'),
        ),
        migrations.AlterField(
            model_name='account',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
