# Generated by Django 2.1.7 on 2020-01-05 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_goods', '0003_auto_20200106_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allow_sale_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 13, 28, 45, 318955), verbose_name='可售时间'),
        ),
    ]
