# Generated by Django 2.1.7 on 2020-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_goods', '0004_auto_20200106_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allow_sale_time',
            field=models.DateTimeField(verbose_name='可售时间'),
        ),
    ]
