# Generated by Django 2.1.7 on 2020-01-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_goods', '0006_auto_20200106_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allow_sale_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='可售时间'),
        ),
    ]
