# Generated by Django 2.1.7 on 2020-01-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=36)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='总价格')),
                ('count', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('trade_status', models.CharField(choices=[(0, 'WAIT_BUYER_PAY'), (1, 'TRADE_CLOSED'), (2, 'TRADE_SUCCESS'), (3, 'TRADE_FINISHED')], default=0, max_length=20, verbose_name='交易状态')),
                ('trade_no', models.CharField(max_length=36, verbose_name='交易号')),
            ],
            options={
                'verbose_name_plural': '订单信息',
            },
        ),
    ]
