# Generated by Django 2.1.7 on 2020-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_order', '0002_orderinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2015, max_digits=7, verbose_name='单价'),
            preserve_default=False,
        ),
    ]
