# Generated by Django 2.1.7 on 2020-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_order', '0004_remove_orderinfo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2009, max_digits=7, verbose_name='单价'),
            preserve_default=False,
        ),
    ]
