# Generated by Django 2.1.7 on 2020-01-12 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_order', '0006_orderinfo_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_status',
            field=models.IntegerField(choices=[(0, '等待支付'), (1, '交易超时'), (2, '交易成功'), (3, '交易完毕')], default=0, max_length=20, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
