# Generated by Django 2.1.7 on 2020-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_order', '0009_auto_20200305_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_mode',
            field=models.IntegerField(choices=[(0, '支付宝'), (1, '微信'), (2, '银行卡')], default=0, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_no',
            field=models.CharField(max_length=36, verbose_name='订单编号'),
        ),
    ]
